[package]
name = "small_gicp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.6"
ros_pointcloud2 = "0.5.0-rc.3"


[build-dependencies]
bindgen = "0"
cc = "1"
pkg-config = "0.3"

[dev-dependencies]
rand = "0.8.5"
approx = "0.5.1"
